### ISSUE TITLE
what the steps to run?

### ISSUE THREAD

**Issue by SeekPoint** [guotong1988/Chinese-NER-joint-intent#11]

**Comment by guotong1988** [comment]
`train.py`

**Comment by SeekPoint** [comment]
after run process1,2,3
then run train.py, it reports:


  File "train.py", line 46, in <module>
    y_intent_val, seq_len_train, seq_len_valid = helper.get_train(train_path=train_path, val_path=val_path, input_tag_path=pathin_tag, val_tag_path=val_tag_path, input_intent_path=pathin_intent, valid_intent_path=pathval_intent, seq_max_len=num_steps)
  File "/Users/yuanke/ghSrc/Chinese-NER-joint-intent/helper.py", line 477, in get_train
    char2id, id2char, label2id, id2label = build_map(train_path)
  File "/Users/yuanke/ghSrc/Chinese-NER-joint-intent/helper.py", line 303, in build_map
    f = open("elmo/vocab.txt",encoding="utf-8",mode="r")
FileNotFoundError: [Errno 2] No such file or directory: 'elmo/vocab.txt'

**Comment by guotong1988** [comment]
This repo is just a lab-style code.

**Comment by SeekPoint** [comment]
so, how to generates vocab.txt base on the raw data

**Comment by guotong1988** [comment]
I forget. You can produce your own vocab.

**Comment by SeekPoint** [comment]
ok, I am not waste time on this.
